// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Genre struct {
	ID   int32
	Name string
	Code string
}

type Music struct {
	ID        uuid.UUID
	Name      string
	Artist    string
	CreatedAt time.Time
	Genre     int32
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	ApiKey    string
}
