// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: music.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMusic = `-- name: CreateMusic :one
INSERT INTO music (id, name, artist, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, artist, created_at
`

type CreateMusicParams struct {
	ID        uuid.UUID
	Name      string
	Artist    string
	CreatedAt time.Time
}

func (q *Queries) CreateMusic(ctx context.Context, arg CreateMusicParams) (Music, error) {
	row := q.db.QueryRowContext(ctx, createMusic,
		arg.ID,
		arg.Name,
		arg.Artist,
		arg.CreatedAt,
	)
	var i Music
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Artist,
		&i.CreatedAt,
	)
	return i, err
}
