// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: tracks.sql

package database

import (
	"context"
	"time"
)

const createTrack = `-- name: CreateTrack :one
INSERT INTO tracks (rank, title, artist, uri, date)
VALUES ($1, $2, $3, $4, $5)
	RETURNING rank, title, artist, uri, date
`

type CreateTrackParams struct {
	Rank   int32
	Title  string
	Artist string
	Uri    string
	Date   time.Time
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, createTrack,
		arg.Rank,
		arg.Title,
		arg.Artist,
		arg.Uri,
		arg.Date,
	)
	var i Track
	err := row.Scan(
		&i.Rank,
		&i.Title,
		&i.Artist,
		&i.Uri,
		&i.Date,
	)
	return i, err
}

const getTracksByDate = `-- name: GetTracksByDate :many
SELECT rank, title, artist, uri, date FROM tracks WHERE date = $1
`

func (q *Queries) GetTracksByDate(ctx context.Context, date time.Time) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, getTracksByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.Rank,
			&i.Title,
			&i.Artist,
			&i.Uri,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
